apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: exam-dante
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce

---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pv-claim
#  namespace: exam-dante
#spec:
#    storageClassName: csi-hostpath-sc
#    accessModes:
#        - ReadWriteOnce
#    resources:
#        requests:
#        storage: 10Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: exam-dante
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: pv-volume
  volumes:
    - name: pv-volume
      persistentVolumeClaim:
        claimName: pv-claim