apiVersion: v1 # 디스크립터는 쿠버네티스 API 버전 v1 을 준수함
kind: Pod # 오브젝트 종류가 파드
metadata:
  name: kubia-manual # 파드명
spec:
  containers:
    - name: kubia # 컨테이너명
      image: hyooo/kubia # 컨테이너 생성을 위한 이미지
      ports:
        - containerPort: 8080 # 애플리케이션이 수신하는 포트
          protocol: TCP