# Create a redis pod and expose it on port 6379
apiVersion: v1
kind: Pod
metadata:
  name: redis-dante-exam10
  namespace: exam-dante
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379