apiVersion: v1
kind: Pod
metadata:
  name: kubia
spec:
  containers:
    - name: kubia-http
      image: hyooo/kubia
      ports:
        - containerPort: 8080
    - name: kubia-https
      image: hyooo/kubia
      ports:
        - containerPort: 8443