apiVersion: v1
kind: Secret
metadata:
  name: super-secret
type: Opaque
data:
  password: bob

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-file
spec:
  volumes:
    - name: super-secret
      secret:
        secretName: super-secret
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: super-secret
          readOnly: true
          mountPath: "/secrets"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-env
spec:
  containers:
    - name: redis
      image: redis
      env:
        - name: CONFIDENTIAL
          secretKeyRef:
            name: super-secret
            key: password