apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3 # 파드 인스턴스 수
  selector: # 파드 셀렉터로 레플리케이션컨트롤러가 관리하는 파드 선택
    app: kubia
  template: # 파드 템플릿
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: hyooo/kubia
          ports:
            - containerPort: 8080