apiVersion: apps/v1
kind: Deployment
metadata:
  name: dante-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: dante-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
          volumeMounts:
            - mountPath: "/etc/dante-configmaps"
              name: dante-configmaps
              readOnly: true
      volumes:
        - name: dante-configmaps
          configMap:
            name: dante-configmaps