apiVersion: v1
kind: Pod
metadata:
  name: non-persistent-redis
  namespace: exam-dante
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: cache-control
          mountPath: /data/redis
  volumes:
    - name: cache-control
