# Create a new deployment called nginx-deploy, with image nginx:1.16 and 1 replica. Record the version.
# Next upgrade the deployment to version 1.17 using rolling update.
# Make sure there version update is recorded int the resource annotation.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
