spring:
  application:
    name: hello-spring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL} # .env 와 EnvFile 플러그인을 사용하는데 Enable experimental integrations 옵션을 켜야 .env 가 적용된다.
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true # 전송 쿼리 확인
    hibernate:
      ddl-auto: update