spring:
  application:
    name: hello-spring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    url: ${MYSQL_URL}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true # 전송 쿼리 확인
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true # 테이블 생성 후 data.sql 실행 옵션